import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import MainLayout from '@src/components/layout/main'
import NetworkInfo from '@components/landing/NetworkInfo'
import TransactionInfo from '@components/landing/TransactionInfo'
import { useEthers } from '@usedapp/core'
import { Box } from '@mui/material'
import ConnectWalletButton from '@src/components/shared/ConnectWalletButton'

const ConnectAccount = () => {
  return (
    <Box
      sx={{
        flexGrow: 1,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <ConnectWalletButton size='large' />
    </Box>
  )
}

const Home: NextPage = () => {
  const { account } = useEthers()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainLayout>
        <>
          {account && <NetworkInfo />}
          {account && <TransactionInfo />}
          {!account && <ConnectAccount />}
        </>
      </MainLayout>
    </>
  )
}

export default Home
