import type { NextPage } from 'next'
import Head from 'next/head'
import MainLayout from '@src/components/layout/main'
import SendETHForm from '@src/components/forms/SendETH'

const Transfer: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainLayout>
        <SendETHForm />
      </MainLayout>
    </>
  )
}

export default Transfer
